### ISSUE TITLE
Diff display incorrect

### ISSUE THREAD

**Issue by grosjo** [websvnphp/websvn#130] opened 2020-11-07 15:33 UTC
Hi
The "Compare with previous" shows wrong color of the differences
(using php 7.3.23)
See screenshot as an example
![Screenshot from 2020-11-07 15-31-52](https://user-images.githubusercontent.com/2287111/98445251-96e85780-210e-11eb-937d-d17a9b3efb94.png)

**Comment by michael-o** [comment] 2020-11-07 15:58
Why do you consider the color to be wrong? What is right?

**Comment by grosjo** [comment] 2020-11-07 16:03
Look at the actual differences : 
- The line removed is line 436 (not in color)
- The line 434 (in color) got no changes

This is the exact same issue on all files : the color is shifted by several lines

**Comment by ams-tschoening** [comment] 2020-11-08 17:43
I can reproduce this, looks like an index/offset-problem somewhere in [include/diff_inc.php::diff_result](https://github.com/websvnphp/websvn/blob/5049bbccb5ca0d60bc565dab25391ef855f8e085/include/diff_inc.php#L111) most likely. In the following screenshot, I removed empty lines between what is line 8 and 9 in the right revision, but the left window gets this wrong.

![Bild_2020-11-08_183135](https://user-images.githubusercontent.com/6223655/98472055-a17b1d80-21f0-11eb-8966-c6bb38943c72.png)

OTOH, other changes don't seem to be detected properly as well, like can be seen in the following screenshot. In line 11, new text appears without any coloring:

![Bild_2020-11-08_183333](https://user-images.githubusercontent.com/6223655/98472089-e7d07c80-21f0-11eb-9416-c05f4891078b.png)

**Comment by k10blogger** [comment] 2020-11-08 20:01
This is working pretty well for me:
Have a look at my snapshot

Spaces detection
![image](https://user-images.githubusercontent.com/4973182/98482994-0eaba480-222b-11eb-857d-04a8a8923599.png)

Changes in text
![image](https://user-images.githubusercontent.com/4973182/98483003-2420ce80-222b-11eb-8b5f-01ead60f37c4.png)

Changes in spelling and line
![image](https://user-images.githubusercontent.com/4973182/98483014-3995f880-222b-11eb-8c3e-2f3ef31acfb0.png)

**Comment by ams-tschoening** [comment] 2020-11-09 07:48
Let's have a closer look at who generates the diff: WebSVN supports the PEAR package `Text_Diff` or using some diff-binary on the shell. I thought to have `Text_Diff` available, but because PEAR seems pretty broken I don't have and WebSVN falls back to the following shell:

    "C:/Program Files/Git/usr/bin\diff" -U 5 "C:\Users\httpd\AppData\Local\Temp\C77A.tmp" "C:\Users\httpd\AppData\Local\Temp\C70A.tmp"

Things can be checked in `diff_inc.php` at the bottom of the file by simply add something like the following:

	function do_diff($all, $ignoreWhitespace, $highlighted, $newtname, $oldtname, $newhlname, $oldhlname) {
		if (class_exists('Text_Diff')) {
			die('Text_Diff');
			return inline_diff($all, $ignoreWhitespace, $highlighted, $newtname, $oldtname, $newhlname, $oldhlname);
		} else {
			die('Shell');
			return command_diff($all, $ignoreWhitespace, $highlighted, $newtname, $oldtname, $newhlname, $oldhlname);
		}
	}

Once it's known which path is executed and it's the shell one, we need the invoked command as well:

	// Open a pipe to the diff command with $context lines of context:
	$cmd	= $config->diff.$whitespaceFlag.' -U '.$context.' "'.$oldtname.'" "'.$newtname.'"';
        die($cmd);
	$diff	= runCommand($cmd);

Afterwards we can compare results between @k10blogger, @grosjo and myself.

**Comment by grosjo** [comment] 2020-11-09 12:06
My setup does not include the pear package, but the diff (linux) command is used:

diff -U 5 "/tmp/if3Wtq" "/tmp/t6cdKr"

**Comment by k10blogger** [comment] 2020-11-13 09:08
Hi,
I did some digging. I was able to reproduce the issue after i removed the Text_Diff from the server. 
First the correct diff with the Text_Diff
![image](https://user-images.githubusercontent.com/4973182/99049360-c094f900-25bc-11eb-9717-8a80b239968a.png)
Now if i remove and switch to the shell diff this is the output
![image](https://user-images.githubusercontent.com/4973182/99050244-e8d12780-25bd-11eb-8c22-df0e394850cc.png)

**Comment by k10blogger** [comment] 2020-11-13 09:35
@grosjo We have dependency on pear/Text_Diff
You need to have this in the php installation. If you dont have it you can download it separately from here.
https://github.com/pear/Text_Diff
The recommended release is 1.2.2

You can look into your `php.ini` for include_path to find the pear installation or pear include path and add this there. 
Let us know if it works after that.

**Comment by grosjo** [comment] 2020-11-13 11:14
Indeed, installing the pear package resolves the problem.

However, this means the dependency shall create an error (as of now, no warning of any kind)

**Comment by michael-o** [comment] 2020-11-13 11:20
Maybe we should stop relying on `diff(1)` and fail?

**Comment by k10blogger** [comment] 2020-11-13 12:56
That would be one option. But it would still require user to manually add the Text_Diff in the php installtion.
What about using something like this?
https://stackoverflow.com/questions/17219436/run-composer-with-a-php-script-in-browser#:~:text=Yes%20you%20can%20run%20Composer,in%20via%20the%20command%20line.

The idea behind this is we force a composer run from our setup.php and then we can check whether the installation has happen locally to the project and then not run it again ? (Yeah not sure but still an idea?)

**Comment by michael-o** [comment] 2020-11-13 13:17
We have clearly documented what dependencies are required. They all can be installed via PEAR or Composer. If the admin does not, behavior is undefined. I wouldn't put any more effort into it or some autoload magic.

**Comment by grosjo** [comment] 2020-11-13 13:20
What about checking for dependencies in the index.php, and throwing an error in the web page if one is missing ?

**Comment by ams-tschoening** [comment] 2020-11-13 13:21
Guten Tag Siddharth Kaul,
am Freitag, 13. November 2020 um 13:57 schrieben Sie:

> The idea behind this is we force a composer run from our
> setup.php[...]

That's a really bad idea, basic security is that the app can't write
to itself when executed using a web server anyway. Especially these
days with containers and stuff you can't be sure about the executing
environment anyway, which parts of that are read-only etc. If the
"composer.json" shipped witht he app is simply wrong for some reason
and pulls in broken dependencies, the app stops working from one
momen to another.

Don't do that, improve the docs instead and simply tell people about
their wrong/unsupported setup. So if things don't work with a DIFF for
the shell, fix that or remove support for that or make it optional,
but unsupported or alike. Setting things up with using "Text_Diff"
should be easy now that "composer.json" is shipped.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by k10blogger** [comment] 2020-11-13 13:29
yeah okay This is good information to know I didnt know it. : ) 
But the dependency is clearly mentioned in the docs here:
https://websvnphp.github.io/docs/install.html#installation

So i guess no action needed here.

**Comment by k10blogger** [comment] 2020-11-16 15:36
Closing this issue. As nothing to be done here. Please make sure that all dependencies are installed on the host running the websvn. Composer can be used for the same.

**Closed by k10blogger** 2020-11-16 15:36 UTC
Labels: question
